name: ASCII Workflow

on:
  - push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: install Cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay Command
              run: cowsay -f dragon "Run for cover, I am a dragon!...... RAWR" >> dragon.txt

            - name: Test file exists
              run: grep -i "dragon" dragon.txt

            - name: Read the file
              run: cat dragon.txt

            - name: List Repo files
              run: ls -ltra