# Name of the workflow — appears in the GitHub Actions tab
name: First Workflow Updated

# Trigger — this workflow runs whenever code is pushed to any branch
on:
  - push

jobs: 
  # Job ID — the unique name for this job
  first_job:
    name: First Job Updated 
    # Runner — use the latest version of an Ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      # Step 1 — print a welcome message to the console
      - name: updated Welcome Message
        run: echo "Welcome to the CICD world with GitHub Actions"

      # Step 2 — list all files in the current working directory
      - name: List all Files including hidden files
        run: ls -a 

      # Step 3 — print the contents of the dockerfile to the console
      - name: Display curent working directory 
        run: pwd