name: Firt Workflow
on:
  - push

jobs:
  first_job:
    name: DevOps First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: List and read files
        run: |
          echo "My first Github Actions job"
          ls -la
          cat happy.txt
          cat Dockerfile
    